version: '3.9'
services:
  db:
    image: mysql:8.2.0-oracle
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - startup-network
  base-books:
    image: gabriegonza18/base-books
    restart: always
    build: ./Startup
    working_dir: /Startup
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/${DATABASE}?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: ${SQL_USERNAME}
      SPRING.DATASOURCE.PASSWORD: ${SQL_PASSWORD}
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - startup-network
networks:
  startup-network:
    driver: bridge