insert into person (first_name, last_name, enabled, gender, address) values
		('Nicky', 'Kirkhouse', b'1', 'Female', '668 Pennsylvania Court'),
		('Mort', 'Easson', b'0', 'Male', '75362 Mesta Alley'),
		('Raeann', 'Fydoe', b'1', 'Female', '153 Lotheville Alley'),
		('Nesta', 'Edinborough', b'0', 'Female', '64 Acker Street'),
		('Cord', 'Lomond', b'0', 'Male', '261 Mosinee Hill'),
		('Trudey', 'Biffin', b'0', 'Female', '1845 Calypso Parkway'),
		('Janenna', 'Shepherdson', b'0', 'Female', '85 Becker Junction'),
		('Udell', 'Sobieski', b'0', 'Male', '01 Red Cloud Hill'),
		('Ofilia', 'Rooson', b'0', 'Female', '1637 Express Drive'),
		('Kerby', 'Hunnicutt', b'1', 'Male', '84 Stuart Road'),
		('Antonin', 'Eisak', b'0', 'Male', '643 Clove Road'),
		('Edgard', 'Detoc', b'1', 'Male', '5859 Di Loreto Alley'),
		('Sande', 'Santon', b'0', 'Female', '79318 Schlimgen Crossing'),
		('Emmalynne', 'Haquard', b'0', 'Female', '26083 Lindbergh Parkway'),
		('Orv', 'MacShirrie', b'1', 'Male', '61446 Farragut Way'),
		('Jervis', 'Boanas', b'0', 'Male', '301 Fremont Point'),
		('Cathyleen', 'Medway', b'0', 'Female', '092 Truax Place'),
		('Hodge', 'Ourry', b'1', 'Male', '4 Portage Way'),
		('Taryn', 'Andric', b'1', 'Female', '3114 Farragut Park'),
		('Ardene', 'Ambrosoni', b'1', 'Female', '89 Spaight Way'),
		('Wallace', 'Penhall', b'0', 'Male', '8024 Starling Point'),
		('Brock', 'Acheson', b'1', 'Male', '3 Del Mar Street'),
		('Osmond', 'Fenby', b'1', 'Male', '96787 American Trail');